swagger: "2.0"
info:
  title: DevJobs API 
  description: API for dev jobs application
  version: 1.0.0
schemes:
  
paths:
  /jobs/{size}/{page}:
    get:
      parameters:
        - name: size
          in: path
          description: ID of the user
          required: true
          schema:
            type: integer
        - name: page
          in: path
          description: ID of the user
          required: true
          schema:
            type: integer
      summary: Retrieve a list of DevJobs.
      description: Returns an array of DevJobs stored in the database,Each job includes a unique ID, a job title, a job description, and other relevant job details. The page number and number of items per page can be specified in the request URL.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                  required: true
                  example: 1
                company:
                  type: string
                  required: true
                  example: Scoot
                logo:
                  type: string
                  required: true
                  example: 
                logoBackground:
                  type: string
                  required: true
                  example: hsl(36, 87%, 49%)
                position:
                  type: string
                  required: true
                  example: Senior Software Engineer
                postedAt:
                  type: string
                  required: true
                  example: 5h ago
                contract:
                  type: string
                  required: true
                  example: Full Time
                location:
                  type: string
                  required: true
                  example: United States
                website:
                  type: string
                  required: true
                  example: 
                apply:
                  type: string
                  required: true
                  example: 
                description:
                  type: string
                  required: true
                requirements:
                  content:
                    type: string
                    required: true
                  items:
                    - type: string
                      required: true
                role:
                  content:
                    type: string
                    required: true
                    example: 
                  items:
                    - type: string
                      required: true
                      example: 