swagger: "2.0"
info:
  title: DevJobs API 💼
  description: API for managing dev jobs
  version: 1.0.0
schemes:
  - http
paths:
  /jobs/6/2:
    get:
      summary: Retrieve a paginated list of DevJobs.
      description: Returns an array of DevJobs stored in the database, limited to a specific page and number of items per page. Each job includes a unique ID, a job title, a job description, and other relevant job details. The page number and number of items per page can be specified in the request URL, for example, jobs/6/2 would retrieve the second page of 6 DevJobs.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                  required: true
                  example: 1
                company:
                  type: string
                  required: true
                  example: Scoot
                logo:
                  type: string
                  required: true
                  example: /iamges/scoot.svg
                logoBackground:
                  type: string
                  required: true
                  example: hsl(36, 87%, 49%)
                position:
                  type: string
                  required: true
                  example: Senior Software Engineer
                postedAt:
                  type: string
                  required: true
                  example: 5h ago
                contract:
                  type: string
                  required: true
                  example: Full Time
                location:
                  type: string
                  required: true
                  example: United States
                website:
                  type: string
                  required: true
                  example: https://www.flyscoot.com/en/
                apply:
                  type: string
                  required: true
                  example: https://www.flyscoot.com/en/
                description:
                  type: string
                  required: true
                  example: Scoot is looking for job
                requirements:
                  content:
                    type: string
                    required: true
                    example: The ideal candidate is as passionate about solving challenges through …
                  items:
                    - type: string
                      required: true
                role:
                  content:
                    type: string
                    required: true
                    example: "/iamges/scoot.svg"
                  items:
                    - type: string
                      required: true
                      example: "/iamges/scoot.svg"